### PR TITLE
feat: use Type-Only Imports for types

### LINKED ISSUE #107: [Feature request] Add an option to  use Type-Only Imports
## Description

If we use the TypeScript compiler option `"importsNotUsedAsValues": "error"`, imports that are not type-only will result in an error.

## Describe the solution you'd like

Adding an option to  use Type-Only Imports like `--useTypeOnlyImports`.

## Describe alternatives you've considered

- Add `// @ts-nocheck` to the top of the generated `$path.ts` file
- Replace `import` to `import type` by using script.

### PR DESCRIPTION
**Pull request by dqn**
## Types of changes

- [ ] Bug fixes
  - resolves #
- [x] Features
  - resolves #107 
- [ ] Maintenance
- [ ] Documentation

## Changes

- Add `useTypeOnlyImports` option.

## Community note

Please upvode with reacting as :+1: to express your agreement.

### CODE REVIEW

**Comment by LumaKernel** [comment]
We appreciate your contribution.
We're going to discuss about adding `--useTypeOnlyImports` option to `aspida` (https://github.com/aspida/aspida/issues/697), `pathpida` (https://github.com/aspida/pathpida/issues/107), and frourio (https://github.com/frouriojs/frourio/issues/198).
My opinion is to default to true this option. In this case, we should decide how naming the flag. (like `--noTypeImports`, `--legacyTypeImports`)
Another option is to drop support for TS versions that can't use type imports.

CC @hashue @solufa

**Comment by LumaKernel** [comment]
Please ignore windows test. We will fix it.

**Comment by LumaKernel** [comment]
Memo: Type-Only Imports and Export was introduced in [TypeScript 3.8](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) (2020/02/21; just 2 years ago)

It's difficult... but I heard pathpida has the most number of users, so it may not be time to decide yet.

I think it is necessary to show warning message if defaulting to true.

**Comment by LumaKernel** [comment]
https://github.com/aspida/pathpida/pull/108

I'll work on this as
- Defaulting to true
- Set `--useTypeOnlyImports=false` to disable
- Check `require('typescript/package.json').version` to show warning message (or change default value of this)

I'll start working on aspida, frourio, and pathpida in this order. I'll push changes to this PR but I welcome your extra changes.

**Comment by LumaKernel** [comment]
Hello. We decided to drop support for TS 3.7 or older.

member notice: do not bump to v1. place warning message on readme.

**Comment by dqn** [comment]
OK, I understand your decision. I'll fix this changes.

**Review by LumaKernel — APPROVED** [review]
Okay. Thank you for your devotion. 👍

**Pull request merged**
